server:
  port: 8080

spring:
  application:
    name: eureka-client

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
  instance:
    hostname: localhost
    instanceId: 1
    