server:
  port: 8888

spring:
 application:
    name: eureka-client-2

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9002/eureka/
  instance:
    hostname: localhost
    